# Generated by Django 4.2.5 on 2023-09-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='logo',
        ),
    ]
